### ISSUE TITLE
Not setting wallpaper on all Desktops on macOS

### ISSUE THREAD

**Issue by FormalSnake** [sindresorhus/wallpaper#95] opened 2024-03-01 10:35 UTC
It only sets it on one Desktop.
Here is my code:
```js
import { getWallpaper, setWallpaper } from "wallpaper";
import fs from "fs"

var files = fs.readdirSync('./wallpapers/')

const options = {
  screen: 'all'
};

export function changePaper(){
let img = "wallpapers/" + files[Math.floor(Math.random() * files.length)]
  setWallpaper(img, options)
  console.log(img)
}

changePaper()

```

**Comment by sindresorhus** [comment] 2024-03-01 14:15
Duplicate of https://github.com/sindresorhus/wallpaper/issues/31

**Closed** 2024-03-01 14:21 UTC
